# Shell variables
# Generated by 'wal'
wallpaper='/home/anthony/wallpapers/15.jpg'

# Special
background='#101010'
foreground='#d9d9d9'
cursor='#d9d9d9'

# Colors
color0='#101010'
color1='#AE4630'
color2='#8B807F'
color3='#929292'
color4='#9E9F9F'
color5='#B0B0B0'
color6='#B9C1C2'
color7='#d9d9d9'
color8='#979797'
color9='#AE4630'
color10='#8B807F'
color11='#929292'
color12='#9E9F9F'
color13='#B0B0B0'
color14='#B9C1C2'
color15='#d9d9d9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
