--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/anthony/wallpapers/24.jpg"

-- Special
background="#030912"
foreground="#88b5d8"
cursor="#88b5d8"

-- Colors
color0="#030912"
color1="#195D9E"
color2="#19629A"
color3="#21649A"
color4="#1B75B6"
color5="#2175B5"
color6="#1C7BC2"
color7="#88b5d8"
color8="#5f7e97"
color9="#195D9E"
color10="#19629A"
color11="#21649A"
color12="#1B75B6"
color13="#2175B5"
color14="#1C7BC2"
color15="#88b5d8"
