# Shell variables
# Generated by 'wal'
wallpaper='/home/anthony/wallpapers/22.jpg'

# Special
background='#11100e'
foreground='#e0ece6'
cursor='#e0ece6'

# Colors
color0='#11100e'
color1='#8AA473'
color2='#607985'
color3='#719994'
color4='#91B197'
color5='#AACDA6'
color6='#B3D5CA'
color7='#e0ece6'
color8='#9ca5a1'
color9='#8AA473'
color10='#607985'
color11='#719994'
color12='#91B197'
color13='#AACDA6'
color14='#B3D5CA'
color15='#e0ece6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
