# Shell variables
# Generated by 'wal'
wallpaper='/home/anthony/wallpapers/34.jpg'

# Special
background='#0f0c0d'
foreground='#d0c3da'
cursor='#d0c3da'

# Colors
color0='#0f0c0d'
color1='#694756'
color2='#705064'
color3='#865F73'
color4='#7A6292'
color5='#907297'
color6='#A68AB4'
color7='#d0c3da'
color8='#918898'
color9='#694756'
color10='#705064'
color11='#865F73'
color12='#7A6292'
color13='#907297'
color14='#A68AB4'
color15='#d0c3da'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
