--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/anthony/wallpapers/38.png"

-- Special
background="#020109"
foreground="#f0ecc9"
cursor="#f0ecc9"

-- Colors
color0="#020109"
color1="#645EA8"
color2="#9C5EAF"
color3="#DF63A8"
color4="#A754D0"
color5="#E86AD2"
color6="#51A2CA"
color7="#f0ecc9"
color8="#a8a58c"
color9="#645EA8"
color10="#9C5EAF"
color11="#DF63A8"
color12="#A754D0"
color13="#E86AD2"
color14="#51A2CA"
color15="#f0ecc9"
