--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/anthony/wallpapers/34.jpg"

-- Special
background="#0f0c0d"
foreground="#d0c3da"
cursor="#d0c3da"

-- Colors
color0="#0f0c0d"
color1="#694756"
color2="#705064"
color3="#865F73"
color4="#7A6292"
color5="#907297"
color6="#A68AB4"
color7="#d0c3da"
color8="#918898"
color9="#694756"
color10="#705064"
color11="#865F73"
color12="#7A6292"
color13="#907297"
color14="#A68AB4"
color15="#d0c3da"
